const CONFIG = {
  BASE_URL: 'CHANGE_ME',
  API_BASE: 'CHANGE_ME',
  JELLYFIN_URL: 'CHANGE_ME',
  JELLYFIN_API_KEY: 'CHANGE_ME',
  JELLYFIN_SERVER_ID: 'CHANGE_ME',
  OS_API_KEY: 'CHANGE_ME',
  OS_USERNAME: 'CHANGE_ME',
  OS_PASSWORD: 'CHANGE_ME'
};
